name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Check mypy
        run: |
          python -m mypy --strict .

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install openscad
        run: |
          sudo apt update && sudo apt install openscad -y
      - name: Test with unittest
        run: |
          python -m unittest discover tests/

  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install openscad
        run: |
          curl.exe --output openscad.zip --url https://files.openscad.org/OpenSCAD-2021.01-x86-64.zip
          tar -xf openscad.zip
          move "OpenSCAD-2021.01-x86-64" "C:\Program Files\Openscad"
      - name: Test with unittest
        run: |
          python -m unittest discover tests/
